# Site settings
title: NoonGam's Blog
name: Developer Woo,Dong-Gun # your name
email: wodonggun@gmail.com  # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "/wodonggun.github.io" # the subpath of your site, e.g. /blog
url: "https://wodonggun.github.io" # the base hostname & protocol for your site
twitter_username: Woodonggun # your Twitter username
github_username: wodonggun # your Github username
disqus_username: wodonggun   # your disqus username

google-analytics: UA-121952650-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
